name: fastor_app_ui_widget

version: 1.3.61
homepage: https://github.com/AbdallahAndroid/fastor_app_ui_widget
#homepage: https://fastor-app.com

## Fix Analytics Issue: description field in your package's pubspec.yaml file between 60 and 180 characters
description: Coding Faster By Build Fast UI Widget.  Reduce 28% of chars in writing code & lines breaks. Basics ui widget with extra feature not found at regular widget.


## Fix Analytics Issue
repository: https://github.com/AbdallahAndroid/fastor_app_ui_widget


environment:
#  sdk: ">=2.17.3 <3.0.0"   #flutter version 3.0.2
  sdk: ">=2.17.0 <3.0.0"   #flutter version 3.0.0
  flutter: ">=1.17.0"


TextFieldEmailOrPhoneFastor:
  dart:
dependencies:
  flutter:
    sdk: flutter

  #-------------------------------------------------- abdallah copy/past
  hexcolor:
  universal_io:
  cached_network_image:
  shared_preferences: #^2.0.15
  flutter_spinkit: #^5.1.0
  need_resume:
  internet_connection_checker:
  country_code_picker:
  timezone_to_country:
  country_dial_code:
  http:
  dio:
  pretty_dio_logger: ^1.1.1
  cross_file: # ^0.3.3+4
  intl: # ^0.18.1
  clipboard:

  #animate
  shimmer_animation: 2.1.0
  awesome_dialog: 3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

false_secrets:
  - /lib/firebase_options.dart


flutter:
