name: fastor_app_ui_widget

version: 1.3.45
homepage: https://github.com/AbdallahAndroid/fastor_app_ui_widget
#homepage: https://fastor-app.com

description: >-
  Coding Faster By Build Fast UI Widget.

environment:
#  sdk: ">=2.17.3 <3.0.0"   #flutter version 3.0.2
  sdk: ">=2.17.0 <3.0.0"   #flutter version 3.0.0
  flutter: ">=1.17.0"


TextFieldEmailOrPhoneFastor:
  dart:
dependencies:
  flutter:
    sdk: flutter

  #other
  hexcolor:
  #easy_localization: cause null safty error
  universal_io:
  cached_network_image:
  shared_preferences: #^2.0.15
  flutter_spinkit: #^5.1.0
  need_resume:
  internet_connection_checker:

  # phone mobile country
  country_code_picker:
  timezone_to_country:
  country_dial_code:

  #chart
  fl_chart: #^0.62.0

  #firebase
#  firebase_analytics:
#  firebase_core:

  #fastor sub library
  log_debug:

  #network
  http:

  # dio versions
  dio:
#  dio: ^5.0.0  # timeOut take object Duration
  # dio: ^4.0.6 # timeOut take just integer

  pretty_dio_logger: ^1.1.1
  cross_file: # ^0.3.3+4

  # plugin stop supported, so copied to fastor hard copy
  # flutter_clean_calendar: # ^1.1.0
  intl: # ^0.18.1
  clipboard:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

false_secrets:
  - /lib/firebase_options.dart


flutter:
