// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaTm0GjVQXhA36uk14hgF3H6wGUIkspFI',
    appId: '1:962560185260:web:a6bfbf9c8979c3a018e009',
    messagingSenderId: '962560185260',
    projectId: 'abdallah-android',
    authDomain: 'abdallah-android.firebaseapp.com',
    databaseURL: 'https://abdallah-android.firebaseio.com',
    storageBucket: 'abdallah-android.appspot.com',
    measurementId: 'G-7J2RB6ZEBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJgh9YcVd31uRZKp41Vgb7VlkSBLdN1GM',
    appId: '1:962560185260:android:0f7197fe7b0f992418e009',
    messagingSenderId: '962560185260',
    projectId: 'abdallah-android',
    databaseURL: 'https://abdallah-android.firebaseio.com',
    storageBucket: 'abdallah-android.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe4gRmR39_Jxv15MigGtLgjvUy_8_9c9o',
    appId: '1:962560185260:ios:2367c9b31935f92a18e009',
    messagingSenderId: '962560185260',
    projectId: 'abdallah-android',
    databaseURL: 'https://abdallah-android.firebaseio.com',
    storageBucket: 'abdallah-android.appspot.com',
    androidClientId: '962560185260-vbjnmnlk0n8ud0tasitq1g8pcnm6j3rk.apps.googleusercontent.com',
    iosClientId: '962560185260-lpkc3kntlk98m5fpdrp0ssfvn8bkp77a.apps.googleusercontent.com',
    iosBundleId: 'com.fastor.app',
  );
}
